apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
  namespace: {{$.Chart.Name}}-space
spec:
  selector:
    role: {{.Chart.Name}}-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.greeter.pod.port}}
